name: Build Squidify App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [linux, windows, macos]
        include:
          - os: linux
            runner: ubuntu-latest
            platform: linux
          - os: windows
            runner: windows-latest
            platform: windows
          - os: macos
            runner: macos-latest
            platform: mac

    name: Build for ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Build app with Nativefier (Linux/macOS)
        if: matrix.os != 'windows'
        run: |
          mkdir output
          nativefier \
            --name "Squidify" \
            --platform=${{ matrix.platform }} \
            --resizable \
            --enable-dev-tools \
            --single-instance \
            --tray \
            --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" \
            --chromium-args="--disable-http2 --disable-quic --disable-features=QUIC,HTTP3 --enable-features=HttpProtocolNegotiation" \
            "https://squidify.org" output/

      - name: Build app with Nativefier (Windows)
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          mkdir output
          nativefier `
            --name "Squidify" `
            --platform=windows `
            --resizable `
            --enable-dev-tools `
            --single-instance `
            --tray `
            --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" `
            --chromium-args="--disable-http2 --disable-quic --disable-features=QUIC,HTTP3 --enable-features=HttpProtocolNegotiation" `
            "https://squidify.org" output/

      - name: Rename Nativefier output folder to fixed name for NSIS script (Windows)
        if: matrix.os == 'windows'
        shell: bash
        run: |
          folder=$(find output -maxdepth 1 -type d -name '*win32-x64' | head -n 1)
          echo "Found folder: $folder"

          if [ "$folder" != "output/Squidify-win32-x64" ]; then
            echo "Renaming $folder to output/Squidify-win32-x64"
            mv "$folder" output/Squidify-win32-x64
          else
            echo "Folder already named correctly. No rename needed."
          fi

      - name: Build Windows installer with NSIS
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

      - name: Zip app for macOS (if applicable)
        if: matrix.os == 'macos'
        run: |
          cd output
          zip -r squidify-macos.zip ./*

      # Upload artifacts separately on Windows
      - name: Upload Nativefier output artifact (Windows)
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: squidify-win32-x64
          path: output/Squidify-win32-x64

      - name: Upload NSIS installer artifact (Windows)
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: squidify-installer
          path: output/SquidifyInstaller.exe

      # Upload artifacts for Linux and macOS (single artifact)
      - name: Upload artifact (Linux/macOS)
        if: matrix.os != 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: squidify-${{ matrix.os }}
          path: output/
