name: Build Squidify App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [linux, windows, macos]
        include:
          - os: linux
            runner: ubuntu-latest
            platform: linux
          - os: windows
            runner: windows-latest
            platform: windows
          - os: macos
            runner: macos-latest
            platform: mac

    name: Build for ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Build app with Nativefier (Linux/macOS)
        if: matrix.os != 'windows'
        run: |
          mkdir -p output
          nativefier \
            --name "Squidify" \
            --platform=${{ matrix.platform }} \
            --resizable \
            --enable-dev-tools \
            --single-instance \
            --tray \
            --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" \
            --chromium-args="--disable-http2 --disable-quic --disable-features=QUIC,HTTP3 --enable-features=HttpProtocolNegotiation" \
            "https://squidify.org" output/

      - name: Build app with Nativefier (Windows)
        if: matrix.os == 'windows'
        shell: bash
        run: |
          mkdir output
          nativefier \
            --name "Squidify" \
            --platform=windows \
            --resizable \
            --enable-dev-tools \
            --single-instance \
            --tray \
            --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" \
            --chromium-args="--disable-http2 --disable-quic --disable-features=QUIC,HTTP3 --enable-features=HttpProtocolNegotiation" \
            "https://squidify.org" output/

      - name: Install NSIS (Windows)
        if: matrix.os == 'windows'
        run: choco install nsis

      - name: Build NSIS installer (Windows)
        if: matrix.os == 'windows'
        run: makensis installer.nsi

      - name: Zip app for macOS (if applicable)
        if: matrix.os == 'macos'
        run: |
          cd output
          zip -r squidify-macos.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: squidify-${{ matrix.os }}
          path: |
            output/
            output/squidify-macos.zip
            SquidifyInstaller.exe
