name: Build Squidify App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]

    name: Build for ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Build app with Nativefier
        run: |
          mkdir output
          nativefier \
            --name "Squidify" \
            --platform=${{ matrix.os }} \
            --resizable \
            --disable-dev-tools \
            --single-instance \
            --tray \
            "https://squidify.org" output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: squidify-${{ matrix.os }}
          path: output/
